//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaSanXuat
    {
        public NhaSanXuat()
        {
            this.Phieunhaps = new HashSet<Phieunhap>();
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MaNSX { get; set; }
        public string TenNSX { get; set; }
        public string Thongtin { get; set; }
        public string Logo { get; set; }
    
        public virtual ICollection<Phieunhap> Phieunhaps { get; set; }
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
